name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile CV
        uses: xu-cheng/latex-action@v2
        with:
          root_file: zpeng_cv.tex
          latexmk_use_xelatex: true
          working_directory: ./LaTeX
      - name: Archive documentation
        uses: actions/upload-artifact@v3
        if: success()
        with:
          name: zpeng_cv
          path: ./LaTeX/zpeng_cv.pdf
      - name: Compile Resume
        uses: xu-cheng/latex-action@v2
        with:
          root_file: zpeng_resume.tex
          latexmk_use_xelatex: true
          working_directory: ./LaTeX
      - name: Archive documentation
        uses: actions/upload-artifact@v3
        if: success()
        with:
          name: zpeng_resume
          path: ./LaTeX/zpeng_resume.pdf
