name: Build LaTeX document

on: [push]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile CV
        uses: xu-cheng/latex-action@v2
        with:
          root_file: zpeng_cv.tex
          latexmk_use_xelatex: true
          working_directory: ./LaTeX
      - name: Archive documentation
        uses: actions/upload-artifact@v3
        if: success()
        with:
          name: zpeng_cv
          path: ./LaTeX/zpeng_cv.pdf
      - name: Compile Resume
        uses: xu-cheng/latex-action@v2
        with:
          root_file: zpeng_resume.tex
          latexmk_use_xelatex: true
          working_directory: ./LaTeX
      - name: Archive documentation
        uses: actions/upload-artifact@v3
        if: success()
        with:
          name: zpeng_resume
          path: ./LaTeX/zpeng_resume.pdf
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './LaTeX/zpeng_cv.pdf'
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './LaTeX/zpeng_resume.pdf'
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './README.md'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
